"use client";

import Link from "next/link";
import { useParams } from "next/navigation";

import { AgreementActions } from "@/components/loans/AgreementActions";
import type { LoanAgreementData } from "@/components/loans/agreement";
import { LoanAgreementDocument } from "@/components/loans/LoanAgreementDocument";
import { Card } from "@/components/ui/Card";
import { Loading } from "@/components/ui/Loading";
import { PageHeader } from "@/components/ui/PageHeader";
import { useApi } from "@/lib/hooks";

const PRINT_CSS = `@media print {
  @page { size: A4; margin: 8mm; }
  #left-sidebar, .navbar-fixed-top, .block-header, .mf-no-print, .card > .header { display: none !important; }
  #main-content { margin: 0 !important; padding: 0 !important; width: 100% !important; }
  html, body, #wrapper, #main-content, .container-fluid, .card, .card > .body { background: #fff !important; box-shadow: none !important; border: 0 !important; padding: 0 !important; }
}`;

/**
 * Loan agreement generated by the system after branch manager approval: printed for the customer to fill and sign,
 * then the signed copy is uploaded (required before the credit officer can approve).
 */
export default function LoanAgreementPage() {
  const { id } = useParams<{ id: string }>();
  const { data, isLoading, error } = useApi<LoanAgreementData>(`loans/${id}/agreement`);

  return (
    <>
      <style>{PRINT_CSS}</style>
      <PageHeader crumbs={["Loan", data?.agreement.loan_number ?? `#${id}`, "Loan Agreement"]} right={<Link href={`/loans/${id}`} className="btn btn-secondary mf-no-print"><i className="icon-arrow-left" /> Loan</Link>} />
      <Card
        title="Loan Agreement"
        actions={data && (
          <div className="mf-no-print">
            <button type="button" className="btn btn-info mr-1 mb-1" onClick={() => window.print()}><i className="icon-printer" /> Print</button>
            <AgreementActions loan={{ id: Number(id), agreement_file: data.agreement.uploaded_file, agreement_available: true, customer_name: data.borrower.full_name }} showPrint={false} />
          </div>
        )}
      >
        {error && <p className="text-danger mb-0">{error.message}</p>}
        {isLoading && <Loading />}
        {data && (
          <>
            <div className={`alert ${data.agreement.uploaded_file ? "alert-success" : "alert-warning"} mf-no-print`}>
              {data.agreement.uploaded_file
                ? <>Signed agreement uploaded {data.agreement.uploaded_at} by {data.agreement.uploaded_by ?? "—"}.</>
                : <>Print this agreement, let the customer fill the blank lines and sign it with the guarantors, then upload the signed PDF. The credit officer cannot approve the loan until it is uploaded.</>}
            </div>
            <LoanAgreementDocument data={data} />
          </>
        )}
      </Card>
    </>
  );
}
