import type { CustomerCategory } from "@/types/customer";

/** Category = rule engine — backend/KYC docs §5/§6. */
export const MOCK_CUSTOMER_CATEGORIES: CustomerCategory[] = [
  {
    id: "cat-boda-boda",
    name: "Boda Boda",
    code: "BODA",
    riskTier: "high",
    sector: "business",
    requiredDocuments: ["driving_license", "motorcycle_registration"],
    dynamicFormSchema: [
      { key: "motorcycle_registration_number", label: "Motorcycle Registration Number", type: "text", required: true },
      { key: "daily_income", label: "Average Daily Income (TZS)", type: "number", required: true },
      { key: "route", label: "Usual Route/Stage", type: "text", required: false },
    ],
    requiresExtraApproval: false,
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "cat-small-entrepreneur",
    name: "Small Entrepreneur",
    code: "SME_SMALL",
    riskTier: "medium",
    sector: "business",
    requiredDocuments: ["business_license"],
    dynamicFormSchema: [
      { key: "business_type", label: "Business Type", type: "text", required: true },
      { key: "business_location", label: "Business Location", type: "text", required: true },
      { key: "daily_income", label: "Average Daily Income (TZS)", type: "number", required: true },
      { key: "collateral", label: "Collateral Description", type: "textarea", required: false },
    ],
    requiresExtraApproval: false,
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "cat-medium-entrepreneur",
    name: "Medium Entrepreneur",
    code: "SME_MEDIUM",
    riskTier: "medium",
    sector: "business",
    requiredDocuments: ["business_license", "financial_statement"],
    dynamicFormSchema: [
      { key: "business_type", label: "Business Type", type: "text", required: true },
      { key: "monthly_turnover", label: "Monthly Turnover (TZS)", type: "number", required: true },
      { key: "years_in_business", label: "Years in Business", type: "number", required: true },
    ],
    requiresExtraApproval: true,
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "cat-public-servant",
    name: "Public Servant",
    code: "PUBLIC_SERVANT",
    riskTier: "low",
    sector: "employment",
    requiredDocuments: ["salary_slip", "employer_letter"],
    dynamicFormSchema: [
      { key: "employer_name", label: "Employer Name", type: "text", required: true },
      { key: "check_number", label: "Check Number", type: "text", required: true },
      { key: "account_number", label: "Salary Account Number", type: "text", required: true },
    ],
    requiresExtraApproval: false,
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "cat-private-sector",
    name: "Private Sector",
    code: "PRIVATE_SECTOR",
    riskTier: "low",
    sector: "employment",
    requiredDocuments: ["salary_slip", "employer_letter"],
    dynamicFormSchema: [
      { key: "employer_name", label: "Employer Name", type: "text", required: true },
      { key: "employment_start_date", label: "Employment Start Date", type: "date", required: true },
    ],
    requiresExtraApproval: false,
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "cat-student",
    name: "Wanachuo (Student)",
    code: "STUDENT",
    riskTier: "high",
    sector: "other",
    requiredDocuments: ["student_id"],
    dynamicFormSchema: [
      { key: "institution_name", label: "Institution Name", type: "text", required: true },
      { key: "guarantor_name", label: "Guarantor Name", type: "text", required: true },
      { key: "guarantor_phone", label: "Guarantor Phone", type: "text", required: true },
    ],
    requiresExtraApproval: true,
    createdBy: "u-admin",
    deletedAt: null,
  },
];
