import type { LoanProduct, LoanProductRepaymentSchedule, CategoryProductEligibility } from "@/types/loan-product";

/** Fully configurable — backend spec §2.3/§6. */
export const MOCK_LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: "prod-boda-working-capital",
    name: "Boda Boda Working Capital",
    code: "BODA_WC",
    interestFormulaId: "if-reducing",
    interestRate: 8,
    minAmount: 100_000,
    maxAmount: 1_000_000,
    minTenureDays: 30,
    maxTenureDays: 180,
    penaltyType: "percentage_of_overdue",
    penaltyRate: 5,
    penaltyGraceDays: 3,
    penaltyCapAmount: 50_000,
    requiresMandate: false,
    status: "active",
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "prod-entrepreneur-growth",
    name: "Entrepreneur Growth Loan",
    code: "SME_GROWTH",
    interestFormulaId: "if-simple",
    interestRate: 12,
    minAmount: 300_000,
    maxAmount: 5_000_000,
    minTenureDays: 60,
    maxTenureDays: 365,
    penaltyType: "percentage_of_overdue",
    penaltyRate: 4,
    penaltyGraceDays: 5,
    penaltyCapAmount: 200_000,
    requiresMandate: false,
    status: "active",
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "prod-salary-advance",
    name: "Salary Advance E-Mandate",
    code: "SALARY_ADVANCE",
    interestFormulaId: "if-flat",
    interestRate: 3,
    minAmount: 200_000,
    maxAmount: 3_000_000,
    minTenureDays: 30,
    maxTenureDays: 365,
    penaltyType: "flat_fee",
    penaltyRate: 10_000,
    penaltyGraceDays: 0,
    penaltyCapAmount: null,
    requiresMandate: true,
    status: "active",
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "prod-public-servant-loan",
    name: "Public Servant Loan",
    code: "PUBLIC_SERVANT_LOAN",
    interestFormulaId: "if-reducing",
    interestRate: 9,
    minAmount: 500_000,
    maxAmount: 8_000_000,
    minTenureDays: 90,
    maxTenureDays: 730,
    penaltyType: "percentage_per_day",
    penaltyRate: 0.5,
    penaltyGraceDays: 5,
    penaltyCapAmount: 300_000,
    requiresMandate: true,
    status: "active",
    createdBy: "u-admin",
    deletedAt: null,
  },
  {
    id: "prod-group-daily",
    name: "Group Daily Micro-Loan",
    code: "GROUP_DAILY",
    interestFormulaId: "if-flat",
    interestRate: 6,
    minAmount: 50_000,
    maxAmount: 500_000,
    minTenureDays: 30,
    maxTenureDays: 90,
    penaltyType: "percentage_of_overdue",
    penaltyRate: 5,
    penaltyGraceDays: 1,
    penaltyCapAmount: 20_000,
    requiresMandate: false,
    status: "active",
    createdBy: "u-admin",
    deletedAt: null,
  },
];

export const MOCK_LOAN_PRODUCT_REPAYMENT_SCHEDULES: LoanProductRepaymentSchedule[] = [
  { id: "lprs-1", loanProductId: "prod-boda-working-capital", repaymentScheduleId: "rs-daily" },
  { id: "lprs-2", loanProductId: "prod-boda-working-capital", repaymentScheduleId: "rs-weekly" },
  { id: "lprs-3", loanProductId: "prod-entrepreneur-growth", repaymentScheduleId: "rs-weekly" },
  { id: "lprs-4", loanProductId: "prod-entrepreneur-growth", repaymentScheduleId: "rs-monthly" },
  { id: "lprs-5", loanProductId: "prod-salary-advance", repaymentScheduleId: "rs-monthly" },
  { id: "lprs-6", loanProductId: "prod-public-servant-loan", repaymentScheduleId: "rs-monthly" },
  { id: "lprs-7", loanProductId: "prod-group-daily", repaymentScheduleId: "rs-daily" },
  { id: "lprs-8", loanProductId: "prod-group-daily", repaymentScheduleId: "rs-group" },
];

export const MOCK_CATEGORY_PRODUCT_ELIGIBILITY: CategoryProductEligibility[] = [
  { id: "cpe-1", customerCategoryId: "cat-boda-boda", loanProductId: "prod-boda-working-capital", maxAmountOverride: null, requiresExtraApproval: false },
  { id: "cpe-2", customerCategoryId: "cat-boda-boda", loanProductId: "prod-group-daily", maxAmountOverride: null, requiresExtraApproval: false },
  { id: "cpe-3", customerCategoryId: "cat-small-entrepreneur", loanProductId: "prod-entrepreneur-growth", maxAmountOverride: 2_000_000, requiresExtraApproval: false },
  { id: "cpe-4", customerCategoryId: "cat-small-entrepreneur", loanProductId: "prod-group-daily", maxAmountOverride: null, requiresExtraApproval: false },
  { id: "cpe-5", customerCategoryId: "cat-medium-entrepreneur", loanProductId: "prod-entrepreneur-growth", maxAmountOverride: null, requiresExtraApproval: true },
  { id: "cpe-6", customerCategoryId: "cat-public-servant", loanProductId: "prod-salary-advance", maxAmountOverride: null, requiresExtraApproval: false },
  { id: "cpe-7", customerCategoryId: "cat-public-servant", loanProductId: "prod-public-servant-loan", maxAmountOverride: null, requiresExtraApproval: false },
  { id: "cpe-8", customerCategoryId: "cat-private-sector", loanProductId: "prod-salary-advance", maxAmountOverride: 1_500_000, requiresExtraApproval: false },
  { id: "cpe-9", customerCategoryId: "cat-student", loanProductId: "prod-group-daily", maxAmountOverride: 200_000, requiresExtraApproval: true },
];
