import type { NotificationTemplate } from "@/types/notification-template";

export const MOCK_NOTIFICATION_TEMPLATES: NotificationTemplate[] = [
  {
    id: "tmpl-loan-approved",
    name: "Loan Approved",
    triggerEvent: "loan_approved",
    channel: "sms",
    subject: null,
    body: "Hongera {{customer_name}}, mkopo wako wa TZS {{amount}} umeidhinishwa. Fedha zitatumwa hivi karibuni.",
    active: true,
    updatedBy: "u-admin",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-loan-rejected",
    name: "Loan Rejected",
    triggerEvent: "loan_rejected",
    channel: "sms",
    subject: null,
    body: "Samahani {{customer_name}}, ombi lako la mkopo halikukubaliwa. Wasiliana na tawi lako kwa maelezo zaidi.",
    active: true,
    updatedBy: "u-admin",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-disbursement-success",
    name: "Disbursement Successful",
    triggerEvent: "disbursement_success",
    channel: "sms",
    subject: null,
    body: "Umepokea mkopo wa TZS {{amount}} kwenye namba {{phone}}. Asante kwa kuchagua Mikopofasta.",
    active: true,
    updatedBy: "u-finance",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-disbursement-failed",
    name: "Disbursement Failed",
    triggerEvent: "disbursement_failed",
    channel: "email",
    subject: "Disbursement failed for {{loan_number}}",
    body: "Disbursement batch {{batch_reference}} failed: {{failure_reason}}. Retry attempt {{attempt_number}} of 3.",
    active: true,
    updatedBy: "u-finance",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-payment-received",
    name: "Payment Received",
    triggerEvent: "payment_received",
    channel: "sms",
    subject: null,
    body: "Tumepokea malipo yako ya TZS {{amount}} kwa mkopo {{loan_number}}. Salio lililobaki: TZS {{balance}}.",
    active: true,
    updatedBy: "u-finance",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-payment-overdue",
    name: "Payment Overdue",
    triggerEvent: "payment_overdue",
    channel: "sms",
    subject: null,
    body: "Malipo yako ya mkopo {{loan_number}} yamechelewa. Tafadhali lipa haraka ili kuepuka adhabu.",
    active: true,
    updatedBy: "u-branch-manager",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-loan-closed",
    name: "Loan Closed",
    triggerEvent: "loan_closed",
    channel: "sms",
    subject: null,
    body: "Hongera {{customer_name}}, umemaliza kulipa mkopo wako {{loan_number}}. Asante!",
    active: false,
    updatedBy: "u-admin",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-loan-applied",
    name: "Loan Application Received",
    triggerEvent: "loan_applied",
    channel: "sms",
    subject: null,
    body: "Ombi lako la mkopo {{loan_number}} limepokelewa na linasubiri uhakiki.",
    active: true,
    updatedBy: "u-loan-officer",
    updatedAt: new Date().toISOString(),
  },
];
