import Link from "next/link";
import { CalendarClock, ReceiptText, Users } from "lucide-react";
import { EmptyState } from "@/components/feedback/empty-state";
import { AccessDeniedState } from "@/components/feedback/access-denied-state";
import { getCurrentUser } from "@/lib/auth/session";
import { hasAnyPermission, hasPermission } from "@/config/permissions";
import { PERMISSIONS } from "@/types/auth";
import { formatMoneyExact, round2 } from "@/lib/domain/money";
import { getAllPayrollRuns } from "@/lib/api/hr";
import { Money, PageHeader, SettingsCard, StatCard, StatusBadge, type StatusTone } from "@/components/settings";
import { SectionNav } from "@/features/ledger/section-nav";
import { hrNavFor } from "@/features/hr/nav-items";
import { GeneratePayrollForm } from "@/features/hr/payroll-actions";

/**
 * Run status carries real meaning here — a draft has not touched the ledger, a
 * finalized run has, and a paid one has left the bank — so each gets a distinct
 * tone from the shared badge rather than a colour invented on this page.
 */
const STATUS_TONE: Record<string, StatusTone> = {
  draft: "warning",
  // Approved but not yet posted: agreed, and still not in the books.
  approved: "info",
  finalized: "info",
  paid: "active",
};

export default async function PayrollPage() {
  const user = await getCurrentUser();
  if (!user || !hasAnyPermission(user, [PERMISSIONS.HR_VIEW, PERMISSIONS.PAYROLL_FINALIZE])) return <AccessDeniedState />;

  const canGenerate = hasPermission(user, PERMISSIONS.PAYROLL_GENERATE);
  // Ordered newest-period-first by the API, with each run's line count and net
  // total computed there so a summary can never disagree with its lines.
  const runs = await getAllPayrollRuns();

  const netAll = round2(runs.reduce((s, r) => s + r.netTotal, 0));
  const staffPaid = runs.reduce((s, r) => s + r.lineCount, 0);
  const unpaid = runs.filter((r) => r.status !== "paid").length;

  return (
    <>
      <PageHeader
        icon={ReceiptText}
        title="Payroll"
        description="HR generates a draft; only Finance can finalize it, and finalizing is what posts to the ledger."
        breadcrumb={[{ label: "Bank", href: "/treasury" }, { label: "Payroll" }]}
        actions={canGenerate ? <GeneratePayrollForm /> : undefined}
      />

      <SectionNav items={hrNavFor(user)} />

      {runs.length > 0 && (
        <div className="grid gap-4 sm:grid-cols-3">
          <StatCard label="Net across all runs" value={formatMoneyExact(netAll)} icon={ReceiptText} tone="accent" />
          <StatCard label="Payslips issued" value={staffPaid} icon={Users} hint={`${runs.length} run${runs.length === 1 ? "" : "s"}`} />
          <StatCard label="Awaiting payment" value={unpaid} icon={CalendarClock} hint="Runs not yet marked paid" />
        </div>
      )}

      <SettingsCard
        title={`Payroll Runs (${runs.length})`}
        description="One run per period. Open a run to see its payslips."
        bodyClassName="p-0 sm:p-0"
      >
        {runs.length === 0 ? (
          <div className="px-5 pb-6 sm:px-6">
            <EmptyState
              icon={ReceiptText}
              title="No payroll runs yet"
              description={
                canGenerate
                  ? "Generate a draft run for a period to get started. A draft posts nothing until Finance finalizes it."
                  : "A run appears here once HR generates a draft for a period."
              }
              className="border-none"
            />
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="st-table w-full border-collapse">
              <thead>
                <tr>
                  <th scope="col">Period</th>
                  <th scope="col">Generated by</th>
                  <th scope="col" className="!text-right">Staff</th>
                  <th scope="col" className="!text-right">Gross</th>
                  <th scope="col" className="!text-right">Deductions</th>
                  <th scope="col" className="!text-right">Net</th>
                  <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
                {runs.map((run) => {
                  // The index eager-loads each run's lines, so gross and
                  // deductions are summed from the server's own figures.
                  const gross = round2(run.lines.reduce((s, l) => s + l.baseSalary + l.commissionAmount + l.allowancesTotal, 0));
                  const deductions = round2(run.lines.reduce((s, l) => s + l.deductionsTotal, 0));
                  return (
                    <tr key={run.id}>
                      <td>
                        <Link
                          href={`/hr/payroll/${run.period}`}
                          className="font-tabular rounded-[var(--st-radius-xs)] font-medium text-[var(--st-accent)] hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--st-accent)]"
                        >
                          {run.period}
                        </Link>
                      </td>
                      {/* A raw user id in a "Generated by" column reads as a
                          defect; the name needs users.manage, which an
                          HR-viewing role does not hold. */}
                      <td className="text-[var(--st-ink-soft)]">
                        {/* Resolved by the API — /users needs a grant these roles do not hold. */}
                        {run.generatedByName ?? <span className="text-[var(--st-ink-faint)]">—</span>}
                      </td>
                      <td>
                        <Money>{run.lineCount}</Money>
                      </td>
                      <td>
                        <Money>{formatMoneyExact(gross)}</Money>
                      </td>
                      <td>
                        <Money muted={deductions === 0}>{deductions === 0 ? "—" : `−${formatMoneyExact(deductions)}`}</Money>
                      </td>
                      <td>
                        <Money strong>{formatMoneyExact(run.netTotal)}</Money>
                      </td>
                      <td>
                        <StatusBadge tone={STATUS_TONE[run.status] ?? "neutral"} className="capitalize">
                          {run.status}
                        </StatusBadge>
                      </td>
                    </tr>
                  );
                })}
                <tr className="st-total-row">
                  <td colSpan={5} className="font-semibold text-[var(--st-ink)]">
                    Total
                  </td>
                  <td>
                    <Money strong>{formatMoneyExact(netAll)}</Money>
                  </td>
                  <td />
                </tr>
              </tbody>
            </table>
          </div>
        )}
      </SettingsCard>
    </>
  );
}
