import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { EmptyState } from "@/components/feedback/empty-state";
import { AccessDeniedState } from "@/components/feedback/access-denied-state";
import { getCurrentUser } from "@/lib/auth/session";
import { hasAnyPermission, hasPermission } from "@/config/permissions";
import { PERMISSIONS } from "@/types/auth";
import { formatMoney, round2 } from "@/lib/domain/money";
import { MOCK_PAYROLL_RUNS, MOCK_PAYROLL_LINES } from "@/lib/mock-data/payroll";
import { MOCK_USERS } from "@/lib/mock-data/users";
import { SectionNav } from "@/features/ledger/section-nav";
import { hrNavFor } from "@/features/hr/nav-items";
import { GeneratePayrollForm } from "@/features/hr/payroll-actions";

const STATUS_TONE: Record<string, string> = {
  draft: "border-amber-500/40 bg-amber-500/10 text-amber-700 dark:text-amber-400",
  finalized: "border-sky-500/40 bg-sky-500/10 text-sky-700 dark:text-sky-400",
  paid: "border-emerald-500/40 bg-emerald-500/10 text-emerald-700 dark:text-emerald-400",
};

export default async function PayrollPage() {
  const user = await getCurrentUser();
  if (!user || !hasAnyPermission(user, [PERMISSIONS.HR_VIEW, PERMISSIONS.PAYROLL_FINALIZE])) return <AccessDeniedState />;

  const canGenerate = hasPermission(user, PERMISSIONS.PAYROLL_GENERATE);
  const userNames = Object.fromEntries(MOCK_USERS.map((u) => [u.id, u.name]));
  const runs = [...MOCK_PAYROLL_RUNS].sort((a, b) => b.period.localeCompare(a.period));

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1>Payroll</h1>
          <p className="text-sm text-muted-foreground">
            HR generates a draft; only Finance can finalize it, and finalizing is what posts to the ledger.
          </p>
        </div>
        {canGenerate && <GeneratePayrollForm />}
      </div>

      <SectionNav items={hrNavFor(user)} />

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Payroll Runs ({runs.length})</CardTitle>
        </CardHeader>
        <CardContent>
          {runs.length === 0 ? (
            <EmptyState title="No payroll runs" description="Generate a draft run for a period to get started." />
          ) : (
            <div className="overflow-x-auto rounded-lg border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Period</TableHead>
                    <TableHead>Generated by</TableHead>
                    <TableHead>Staff</TableHead>
                    <TableHead className="text-right">Gross</TableHead>
                    <TableHead className="text-right">Deductions</TableHead>
                    <TableHead className="text-right">Net</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {runs.map((run) => {
                    const lines = MOCK_PAYROLL_LINES.filter((l) => l.payrollRunId === run.id);
                    const gross = round2(lines.reduce((s, l) => s + l.baseSalary + l.commissionAmount + l.allowancesTotal, 0));
                    const deductions = round2(lines.reduce((s, l) => s + l.deductionsTotal, 0));
                    const net = round2(lines.reduce((s, l) => s + l.netSalary, 0));
                    return (
                      <TableRow key={run.id}>
                        <TableCell>
                          <Link href={`/hr/payroll/${run.period}`} className="font-medium hover:underline">
                            {run.period}
                          </Link>
                        </TableCell>
                        <TableCell>{userNames[run.generatedBy] ?? run.generatedBy}</TableCell>
                        <TableCell>{lines.length}</TableCell>
                        <TableCell className="font-tabular text-right">{formatMoney(gross)}</TableCell>
                        <TableCell className="font-tabular text-right">−{formatMoney(deductions)}</TableCell>
                        <TableCell className="font-tabular text-right font-medium">{formatMoney(net)}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className={`capitalize ${STATUS_TONE[run.status] ?? ""}`}>
                            {run.status}
                          </Badge>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
