import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ReceiptText } from "lucide-react";
import { AccessDeniedState } from "@/components/feedback/access-denied-state";
import { BreadcrumbLabel } from "@/components/layout/breadcrumb-label";
import { getCurrentUser } from "@/lib/auth/session";
import { hasAnyPermission, hasPermission } from "@/config/permissions";
import { PERMISSIONS } from "@/types/auth";
import { formatMoneyExact, round2 } from "@/lib/domain/money";
import { getPayrollRunByPeriod } from "@/lib/api/hr";
import { MOCK_USERS } from "@/lib/mock-data/users";
import { Money, PageHeader, SettingsCard, StatCard, StatusBadge, type StatusTone } from "@/components/settings";
import { SectionNav } from "@/features/ledger/section-nav";
import { hrNavFor } from "@/features/hr/nav-items";
import { PayrollRunActions } from "@/features/hr/payroll-actions";

const STATUS_TONE: Record<string, StatusTone> = {
  draft: "warning",
  finalized: "info",
  paid: "active",
};

/** Pinned so the server and the client format the date identically (React #418). */
const DATE = new Intl.DateTimeFormat("en-GB", {
  timeZone: "Africa/Dar_es_Salaam",
  day: "2-digit",
  month: "short",
  year: "numeric",
});

export default async function PayrollPeriodPage({ params }: { params: Promise<{ period: string }> }) {
  const { period } = await params;
  const user = await getCurrentUser();
  if (!user || !hasAnyPermission(user, [PERMISSIONS.HR_VIEW, PERMISSIONS.PAYROLL_FINALIZE])) return <AccessDeniedState />;

  // The screens are addressed by period; the API is keyed by run id, so the
  // period is resolved against the index. `show` then eager-loads each line's
  // staff, allowances and deductions.
  const run = await getPayrollRunByPeriod(period);
  if (!run) notFound();

  const lines = run.lines;
  /*
   * `generatedBy` is a user id with no name on the resource, and /users needs
   * `users.manage`, which HR-viewing roles do not hold. When the id cannot be
   * resolved the clause is dropped rather than printed raw — "Generated by 7"
   * tells a reader nothing and looks like a defect. Inventing a name would be
   * worse than omitting one.
   */
  const userNames = Object.fromEntries(MOCK_USERS.map((u) => [u.id, u.name]));
  const generatedByName = userNames[run.generatedBy];

  const gross = round2(lines.reduce((s, l) => s + l.baseSalary + l.commissionAmount + l.allowancesTotal, 0));
  const deductions = round2(lines.reduce((s, l) => s + l.deductionsTotal, 0));
  const base = round2(lines.reduce((s, l) => s + l.baseSalary, 0));
  const commission = round2(lines.reduce((s, l) => s + l.commissionAmount, 0));
  const allowances = round2(lines.reduce((s, l) => s + l.allowancesTotal, 0));

  return (
    <>
      <BreadcrumbLabel label={run.period} />

      <PageHeader
        icon={ReceiptText}
        title={`Payroll ${run.period}`}
        description={
          [
            generatedByName ? `Generated by ${generatedByName}` : null,
            run.finalizedAt ? `Finalized ${DATE.format(new Date(run.finalizedAt))}` : null,
          ]
            .filter(Boolean)
            .join(" · ") || "One line per member of staff, exactly as the run posted it."
        }
        breadcrumb={[
          { label: "Bank", href: "/treasury" },
          { label: "Payroll", href: "/hr/payroll" },
          { label: run.period },
        ]}
        actions={
          <>
            <StatusBadge tone={STATUS_TONE[run.status] ?? "neutral"} className="capitalize">
              {run.status}
            </StatusBadge>
            <Link
              href="/hr/payroll"
              className="st-btn st-btn-secondary"
              /* A link, not a button: this navigates, and back-navigation
                 should open in a new tab and be middle-clickable like any
                 other route in the app. */
            >
              <ArrowLeft className="size-4" strokeWidth={1.9} aria-hidden />
              Back to Payroll
            </Link>
          </>
        }
      />

      <SectionNav items={hrNavFor(user)} />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Gross" value={formatMoneyExact(gross)} hint={`${formatMoneyExact(base)} base · ${formatMoneyExact(commission)} commission`} />
        <StatCard label="Allowances" value={formatMoneyExact(allowances)} />
        <StatCard label="Deductions" value={deductions === 0 ? "—" : `−${formatMoneyExact(deductions)}`} />
        <StatCard label="Net payable" value={formatMoneyExact(run.netTotal)} icon={ReceiptText} tone="accent" hint={`${lines.length} payslip${lines.length === 1 ? "" : "s"}`} />
      </div>

      <SettingsCard
        title="Actions"
        description="Who may do what here is decided by role — Finance finalizes and pays; HR only drafts."
      >
        <PayrollRunActions
          runId={run.id}
          status={run.status}
          canGenerate={hasPermission(user, PERMISSIONS.PAYROLL_GENERATE)}
          canFinalize={hasPermission(user, PERMISSIONS.PAYROLL_FINALIZE)}
        />
      </SettingsCard>

      <SettingsCard
        title={`Payslips (${lines.length})`}
        description="One line per member of staff, exactly as the run posted it."
        bodyClassName="p-0 sm:p-0"
      >
        <div className="overflow-x-auto">
          <table className="st-table w-full border-collapse">
            <thead>
              <tr>
                <th scope="col">Staff</th>
                <th scope="col" className="!text-right">Base</th>
                <th scope="col" className="!text-right">Commission</th>
                <th scope="col" className="!text-right">Allowances</th>
                <th scope="col">Deductions</th>
                <th scope="col" className="!text-right">Net</th>
              </tr>
            </thead>
            <tbody>
              {lines.map((line) => (
                <tr key={line.id}>
                  <td>
                    <Link
                      href={`/hr/staff/${line.staffProfileId}`}
                      className="rounded-[var(--st-radius-xs)] font-medium text-[var(--st-ink)] hover:text-[var(--st-accent)] hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--st-accent)]"
                    >
                      {line.staffName ?? line.staffProfileId}
                    </Link>
                  </td>
                  <td>
                    <Money>{formatMoneyExact(line.baseSalary)}</Money>
                  </td>
                  <td>
                    <Money muted={line.commissionAmount === 0}>
                      {line.commissionAmount > 0 ? formatMoneyExact(line.commissionAmount) : "—"}
                    </Money>
                  </td>
                  <td>
                    <Money muted={line.allowancesTotal === 0}>
                      {formatMoneyExact(line.allowancesTotal)}
                    </Money>
                    {line.allowances.length > 0 && (
                      <span className="mt-0.5 block text-right text-[11.5px] capitalize text-[var(--st-ink-faint)]">
                        {line.allowances.map((a) => a.type.replace(/_/g, " ")).join(", ")}
                      </span>
                    )}
                  </td>
                  <td className="text-[12.5px] capitalize text-[var(--st-ink-soft)]">
                    {line.deductions.length === 0 ? (
                      <span className="text-[var(--st-ink-faint)]">—</span>
                    ) : (
                      line.deductions.map((d) => `${d.type.replace(/_/g, " ")} ${formatMoneyExact(d.amount)}`).join(" · ")
                    )}
                  </td>
                  <td>
                    <Money strong>{formatMoneyExact(line.netSalary)}</Money>
                  </td>
                </tr>
              ))}
              <tr className="st-total-row">
                <td className="font-semibold text-[var(--st-ink)]">Total</td>
                <td>
                  <Money strong>{formatMoneyExact(base)}</Money>
                </td>
                <td>
                  <Money strong>{formatMoneyExact(commission)}</Money>
                </td>
                <td>
                  <Money strong>{formatMoneyExact(allowances)}</Money>
                </td>
                <td className="text-[12.5px] text-[var(--st-ink-soft)]">
                  {deductions === 0 ? "—" : `−${formatMoneyExact(deductions)}`}
                </td>
                <td>
                  <Money strong>{formatMoneyExact(run.netTotal)}</Money>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </SettingsCard>
    </>
  );
}
