import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AccessDeniedState } from "@/components/feedback/access-denied-state";
import { BreadcrumbLabel } from "@/components/layout/breadcrumb-label";
import { getCurrentUser } from "@/lib/auth/session";
import { hasAnyPermission, hasPermission } from "@/config/permissions";
import { PERMISSIONS } from "@/types/auth";
import { formatMoney, round2 } from "@/lib/domain/money";
import { MOCK_PAYROLL_RUNS, MOCK_PAYROLL_LINES, MOCK_ALLOWANCES, MOCK_DEDUCTIONS } from "@/lib/mock-data/payroll";
import { MOCK_USERS } from "@/lib/mock-data/users";
import { SectionNav } from "@/features/ledger/section-nav";
import { hrNavFor } from "@/features/hr/nav-items";
import { PayrollRunActions } from "@/features/hr/payroll-actions";
import { staffName } from "@/features/hr/queries";

export default async function PayrollPeriodPage({ params }: { params: Promise<{ period: string }> }) {
  const { period } = await params;
  const user = await getCurrentUser();
  if (!user || !hasAnyPermission(user, [PERMISSIONS.HR_VIEW, PERMISSIONS.PAYROLL_FINALIZE])) return <AccessDeniedState />;

  const run = MOCK_PAYROLL_RUNS.find((r) => r.period === period);
  if (!run) notFound();

  const lines = MOCK_PAYROLL_LINES.filter((l) => l.payrollRunId === run.id);
  const userNames = Object.fromEntries(MOCK_USERS.map((u) => [u.id, u.name]));

  const gross = round2(lines.reduce((s, l) => s + l.baseSalary + l.commissionAmount + l.allowancesTotal, 0));
  const deductions = round2(lines.reduce((s, l) => s + l.deductionsTotal, 0));
  const net = round2(lines.reduce((s, l) => s + l.netSalary, 0));

  return (
    <div className="space-y-4">
      <BreadcrumbLabel label={run.period} />
      <Button variant="ghost" size="sm" nativeButton={false} render={<Link href="/hr/payroll"><ArrowLeft className="size-4" />Back to Payroll</Link>} />

      <SectionNav items={hrNavFor(user)} />

      <Card>
        <CardContent className="flex flex-col gap-4 pt-6 sm:flex-row sm:items-start sm:justify-between">
          <div className="space-y-1">
            <div className="flex flex-wrap items-center gap-2">
              <h1 className="text-lg font-semibold">Payroll {run.period}</h1>
              <Badge variant="outline" className="capitalize">
                {run.status}
              </Badge>
            </div>
            <p className="text-sm text-muted-foreground">
              Generated by {userNames[run.generatedBy] ?? run.generatedBy}
              {run.finalizedAt && ` · finalized ${new Date(run.finalizedAt).toLocaleDateString()}`}
            </p>
          </div>
          <div className="grid grid-cols-3 gap-4 sm:text-right">
            <Fact label="Gross" value={formatMoney(gross)} />
            <Fact label="Deductions" value={`−${formatMoney(deductions)}`} />
            <Fact label="Net" value={formatMoney(net)} />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Actions</CardTitle>
        </CardHeader>
        <CardContent>
          <PayrollRunActions
            runId={run.id}
            status={run.status}
            canGenerate={hasPermission(user, PERMISSIONS.PAYROLL_GENERATE)}
            canFinalize={hasPermission(user, PERMISSIONS.PAYROLL_FINALIZE)}
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Payslips ({lines.length})</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto rounded-lg border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Staff</TableHead>
                  <TableHead className="text-right">Base</TableHead>
                  <TableHead className="text-right">Commission</TableHead>
                  <TableHead className="text-right">Allowances</TableHead>
                  <TableHead>Deductions</TableHead>
                  <TableHead className="text-right">Net</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {lines.map((line) => {
                  const allowances = MOCK_ALLOWANCES.filter((a) => a.payrollLineId === line.id);
                  const deds = MOCK_DEDUCTIONS.filter((d) => d.payrollLineId === line.id);
                  return (
                    <TableRow key={line.id}>
                      <TableCell>
                        <Link href={`/hr/staff/${line.staffProfileId}`} className="font-medium hover:underline">
                          {staffName(line.staffProfileId)}
                        </Link>
                      </TableCell>
                      <TableCell className="font-tabular text-right">{formatMoney(line.baseSalary)}</TableCell>
                      <TableCell className="font-tabular text-right">{line.commissionAmount > 0 ? formatMoney(line.commissionAmount) : "—"}</TableCell>
                      <TableCell className="font-tabular text-right">
                        {formatMoney(line.allowancesTotal)}
                        <span className="ml-1 text-xs text-muted-foreground">({allowances.map((a) => a.type).join(", ")})</span>
                      </TableCell>
                      <TableCell className="text-xs text-muted-foreground">
                        {deds.map((d) => `${d.type.replace(/_/g, " ")} ${formatMoney(d.amount)}`).join(" · ") || "—"}
                      </TableCell>
                      <TableCell className="font-tabular text-right font-medium">{formatMoney(line.netSalary)}</TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div className="space-y-0.5">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="font-tabular text-sm font-semibold">{value}</p>
    </div>
  );
}
